### ISSUE TITLE
Problems of converting volumes

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose#75]
A few problems I discovered specific to `volumes`:

1. In kompose conversion logic, a volume is created as read-only by default. However, in Kubernetes spec, container volumeMounts is read-write by default; same as docker-compose (I believe so from looking at the file format, please correct me if not). 
2. We create `emptyDir` for volumes, but if host is specified (i.e. `HOST:CONTAINER`, see [spec](https://docs.docker.com/compose/compose-file/#/volumes-volume-driver)), shouldn't we use `hostPath` instead?
3. We create a random string (length of 20) for volume names, which it's not readable; also, volume names defined in docker-compose.yml file is ignored.

**Comment by ngtuna** [comment]
Thanks @janetkuo for pointing this out. This is an important part of kompose conversion. Firstly I would say the current volume conversion was outdated a little bit. I just have a quick look at this.

1. Originally compose defined a volume is in ro mode by default (correct me if I am wrong). Now I see it set to rw mode. 
2. I believe there was something missing on volume part when I did refactoring app.go. Take a look into the original code: https://github.com/skippbox/kompose/blob/9bdc4cf2dd516590135cd12bd6bf27816f0bbffd/cli/app/app.go#L415. I will check your PR immediately.
3. Volume name is not defined in [compose v1 format](https://docs.docker.com/compose/compose-file/#/version-1). That's why I created random name. Now with v2 we have named volume. Could you add a switch/check for volume conversion if the compose file is version 1 or 2 as there are some options in volume definition of compose v2 I haven't covered yet.

**Comment by janetkuo** [comment]
I looked closer at the spec and libcompose, the v2 volume you mentioned are in `Project.VolumeConfigs`, which we don't support. The logic I added in #78 is to parse `Project.ServiceConfigs.Volumes` and use the volume name specified there. 

We should add warnings for not supporting VolumeConfigs too (we don't yet).

**Comment by ngtuna** [comment]
@janetkuo Can we close this issue by your merged PRs?

**Comment by janetkuo** [comment]
Yes
